services:
  - docker: required

script:
- docker run --mount src=$TRAVIS_BUILD_DIR/docs,target=/docs,type=bind alexanderonbysh/latex-base bash -c "pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-directory=. thesis.tex"

before_deploy:
  - git config --local user.name "AlexanderOnbysh"
  - git config --local user.email "alexander.onbysh@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: /docs/thesis.pdf
  name: Build $(date +'%d.%m.%Y %R')
  skip_cleanup: true
  on:
    branch: master
