sudo:       required
language:   generic
services:   docker

tex-config:
- build-pattern=./thesis.tex
- packages=cancel, exam

script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small